Update azure-pipelines.yml for Azure Pipelines

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -29,7 +29,28 @@ jobs:
       sshPublicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDj2ZF+ASvxz/qhUTIJ0yO12YsYpcj6FSrOwBrnghFF38XwnW4gVuGt7pIYRQu/jM6O/LE9/aFp1ZZSws/NSxEccLNujpgWtJWG7Nklgc91SK82U/Y2Jbq8Oplgx5LvozCzvmj5BvEwcOeOE19p0AFvoBTD+ymE5WBx9tS0Ha84Yx9GFXf799bgQyQ1xu7x2vDDrtMJFeCT05pUrdPWuNEKXqpgwgdpRZ4/KMdM6WcsaZhXWYq1fzvwmdW+m3rmxa+agVHR9gQjY9Fm3valsiNzx+Yl+fC1pKOH+O/bnanZQGOIe4hAaAgpbmz8qhZAV/kS33sFT9joaVjE/pjjrj8ulXN8+JBISdAYdCc6vj3fF5s5imx2/fGnOL5N8B05oOu63E55BqL/7D9aWA16P8fPQ0PaL290+laIGJZSMDueyCt/vs2bXvIBfQkH2KRQ1DjLfiD/2O9NJ6Pe2LRPsyF0PSz2U+8oKuCHDk2FIC3efOUThEtBo111uoYX1axzNXJsjVdYN+fQQTa46xX5F1fhCdqe5ca0VEHvKQR2LYZqTH3NN93jDeqkahR9ApqQeAXX3cjSJv9kxUOVMhYxR7Z4oTeZDjmecNAIkSujrbdrGRscogpEqzLLyOcNSm25+4QPYn+jkrWOnEglGmVBLt3oIjVXHMG3N4t8l21TEHnVXw== cxwtool@microsoft.com'
       sshKeySecureFile: 'id_rsa_cxwtool'
   - task: CmdLine@2
-    displayName: Command Line Script
     inputs:
-      script: "git config --local user.name \"CXWTool Service Account\"\ngit config --local user.email \"cxwtool@microsoft.com\"\n\ngit remote add ssh git@github.com:MicrosoftDocs/powerquery-docs-pr.git\n\ngit checkout main\ngit pull ssh main\n\ngit checkout live\ngit pull ssh live\n\ngit merge main\n\nCONFLICTS=$(git ls-files -u | wc -l)\nif [ \"$CONFLICTS\" -gt 0 ] ; then\n   echo \"There is a merge conflict. Aborting\"\n   git merge --abort\n   exit 1\nelse\n    echo \"Merge OK\"\n   git push ssh live  \nfi\n\n"
+      script: |
+        git config --local user.name "CXWTool Service Account"
+        git config --local user.email "cxwtool@microsoft.com"
+        
+        git remote add ssh git@github.com:MicrosoftDocs/partner-center-pr.git
+        
+        git checkout main
+        git pull ssh main
+        
+        git checkout live
+        git pull ssh live
+        
+        git merge main
+        
+        CONFLICTS=$(git ls-files -u | wc -l)
+        if [ "$CONFLICTS" -gt 0 ] ; then
+          echo "There is a merge conflict. Aborting"
+          git merge --abort
+          exit 1
+        else
+            echo "Merge OK"
+          git push ssh live  
+        fi
 ...
